[package]
name = "Rust_ASL_MNIST"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
candle-core = "0.5.1"
candle-nn = "0.5.1"
candle-optimisers = "0.5.0"
csv = "1.3.0"
rand = "0.8.5"
serde = "1.0.203"
shuffle = "0.1.7"
